server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse-management
    username: admin
    password: admin1813
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        open-in-view: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        type: trace
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api/v1
logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.example: DEBUG